// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Test.Grpc {
  public static partial class Test
  {
    static readonly string __ServiceName = "test.grpc.Test";

    static readonly grpc::Marshaller<global::Test.Grpc.Empty> __Marshaller_test_grpc_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Test.Grpc.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Test.Grpc.Ping> __Marshaller_test_grpc_Ping = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Test.Grpc.Ping.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Test.Grpc.Pong> __Marshaller_test_grpc_Pong = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Test.Grpc.Pong.Parser.ParseFrom);

    static readonly grpc::Method<global::Test.Grpc.Empty, global::Test.Grpc.Empty> __Method_OpenTestStream = new grpc::Method<global::Test.Grpc.Empty, global::Test.Grpc.Empty>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "OpenTestStream",
        __Marshaller_test_grpc_Empty,
        __Marshaller_test_grpc_Empty);

    static readonly grpc::Method<global::Test.Grpc.Ping, global::Test.Grpc.Pong> __Method_SendPing = new grpc::Method<global::Test.Grpc.Ping, global::Test.Grpc.Pong>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendPing",
        __Marshaller_test_grpc_Ping,
        __Marshaller_test_grpc_Pong);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Test.Grpc.TestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Test</summary>
    [grpc::BindServiceMethod(typeof(Test), "BindService")]
    public abstract partial class TestBase
    {
      public virtual global::System.Threading.Tasks.Task OpenTestStream(global::Test.Grpc.Empty request, grpc::IServerStreamWriter<global::Test.Grpc.Empty> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Test.Grpc.Pong> SendPing(global::Test.Grpc.Ping request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Test</summary>
    public partial class TestClient : grpc::ClientBase<TestClient>
    {
      /// <summary>Creates a new client for Test</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TestClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Test that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TestClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TestClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TestClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Test.Grpc.Empty> OpenTestStream(global::Test.Grpc.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenTestStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Test.Grpc.Empty> OpenTestStream(global::Test.Grpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_OpenTestStream, null, options, request);
      }
      public virtual global::Test.Grpc.Pong SendPing(global::Test.Grpc.Ping request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendPing(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Test.Grpc.Pong SendPing(global::Test.Grpc.Ping request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendPing, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Test.Grpc.Pong> SendPingAsync(global::Test.Grpc.Ping request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendPingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Test.Grpc.Pong> SendPingAsync(global::Test.Grpc.Ping request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendPing, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TestClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TestClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TestBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_OpenTestStream, serviceImpl.OpenTestStream)
          .AddMethod(__Method_SendPing, serviceImpl.SendPing).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TestBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_OpenTestStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Test.Grpc.Empty, global::Test.Grpc.Empty>(serviceImpl.OpenTestStream));
      serviceBinder.AddMethod(__Method_SendPing, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Test.Grpc.Ping, global::Test.Grpc.Pong>(serviceImpl.SendPing));
    }

  }
}
#endregion
